<?php

use App\Support\PlanFeature;
use App\Support\PlanLimit;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (!Schema::hasTable('subscription_plans')) {
            return;
        }

        $now = now()->toDateTimeString();

        $plans = [
            [
                'code' => 'starter-6m-v2',
                'name' => 'Starter',
                'billing_interval' => 'semiannual',
                'is_active' => true,
                'is_public' => true,
                'is_system' => false,
                'sort_order' => 220,
                'features' => [
                    PlanFeature::MULTI_COMPANY => false,
                    PlanFeature::CONVERSATIONS => true,
                    PlanFeature::CRM => true,
                    PlanFeature::COMMERCE => false,
                    PlanFeature::PROJECT_MANAGEMENT => false,
                    PlanFeature::LIVE_CHAT => true,
                    PlanFeature::SOCIAL_MEDIA => true,
                    PlanFeature::CHATBOT_AI => false,
                    PlanFeature::EMAIL_MARKETING => false,
                    PlanFeature::WHATSAPP_API => false,
                    PlanFeature::WHATSAPP_WEB => false,
                    PlanFeature::ADVANCED_REPORTS => false,
                ],
                'limits' => [
                    PlanLimit::COMPANIES => 1,
                    PlanLimit::BRANCHES => 1,
                    PlanLimit::USERS => 5,
                    PlanLimit::PRODUCTS => 100,
                    PlanLimit::CONTACTS => 2000,
                    PlanLimit::WHATSAPP_INSTANCES => 0,
                    PlanLimit::SOCIAL_ACCOUNTS => 2,
                    PlanLimit::LIVE_CHAT_WIDGETS => 1,
                    PlanLimit::CHATBOT_ACCOUNTS => 0,
                    PlanLimit::EMAIL_INBOX_ACCOUNTS => 0,
                    PlanLimit::EMAIL_CAMPAIGNS => 0,
                    PlanLimit::WA_BLAST_RECIPIENTS_MONTHLY => 0,
                    PlanLimit::EMAIL_RECIPIENTS_MONTHLY => 0,
                    PlanLimit::AI_CREDITS_MONTHLY => 0,
                    PlanLimit::CHATBOT_KNOWLEDGE_DOCUMENTS => 0,
                    PlanLimit::AUTOMATION_WORKFLOWS => 0,
                    PlanLimit::AUTOMATION_EXECUTIONS_MONTHLY => 0,
                ],
                'meta' => [
                    'price' => 894000,
                    'currency' => 'IDR',
                    'tagline' => 'Social inbox, live chat, dan CRM lite untuk 6 bulan kerja yang lebih tenang.',
                    'description' => 'Cocok untuk tim kecil yang sudah siap jalan beberapa bulan ke depan tanpa perlu perpanjang paket setiap bulan.',
                    'highlights' => [
                        'Shared inbox untuk percakapan tim',
                        'CRM lite untuk follow-up lead',
                        'Live chat website',
                        'Social media inbox',
                        'Masa aktif 6 bulan',
                    ],
                    'product_line' => 'omnichannel',
                    'plan_revision' => 'v2',
                    'sales_status' => 'current',
                    'recommended' => false,
                    'audience' => 'Cocok untuk tim kecil yang ingin lebih tenang 6 bulan ke depan',
                ],
            ],
            [
                'code' => 'growth-6m-v2',
                'name' => 'Growth',
                'billing_interval' => 'semiannual',
                'is_active' => true,
                'is_public' => true,
                'is_system' => false,
                'sort_order' => 230,
                'features' => [
                    PlanFeature::MULTI_COMPANY => true,
                    PlanFeature::CONVERSATIONS => true,
                    PlanFeature::CRM => true,
                    PlanFeature::COMMERCE => false,
                    PlanFeature::PROJECT_MANAGEMENT => false,
                    PlanFeature::LIVE_CHAT => true,
                    PlanFeature::SOCIAL_MEDIA => true,
                    PlanFeature::CHATBOT_AI => true,
                    PlanFeature::EMAIL_MARKETING => false,
                    PlanFeature::WHATSAPP_API => true,
                    PlanFeature::WHATSAPP_WEB => true,
                    PlanFeature::ADVANCED_REPORTS => true,
                ],
                'limits' => [
                    PlanLimit::COMPANIES => 1,
                    PlanLimit::BRANCHES => 3,
                    PlanLimit::USERS => 15,
                    PlanLimit::PRODUCTS => 1000,
                    PlanLimit::CONTACTS => 10000,
                    PlanLimit::WHATSAPP_INSTANCES => 1,
                    PlanLimit::SOCIAL_ACCOUNTS => 5,
                    PlanLimit::LIVE_CHAT_WIDGETS => 2,
                    PlanLimit::CHATBOT_ACCOUNTS => 2,
                    PlanLimit::EMAIL_INBOX_ACCOUNTS => 1,
                    PlanLimit::EMAIL_CAMPAIGNS => 0,
                    PlanLimit::WA_BLAST_RECIPIENTS_MONTHLY => 1500,
                    PlanLimit::EMAIL_RECIPIENTS_MONTHLY => 0,
                    PlanLimit::AI_CREDITS_MONTHLY => 500,
                    PlanLimit::CHATBOT_KNOWLEDGE_DOCUMENTS => 25,
                    PlanLimit::AUTOMATION_WORKFLOWS => 0,
                    PlanLimit::AUTOMATION_EXECUTIONS_MONTHLY => 0,
                ],
                'meta' => [
                    'price' => 2094000,
                    'currency' => 'IDR',
                    'tagline' => 'Paket rekomendasi 6 bulan untuk tim yang sudah serius menjalankan omnichannel.',
                    'description' => 'Untuk tim yang ingin lebih tenang menjalankan AI, WhatsApp API, dan WhatsApp Web dari akun bisnis sendiri tanpa perpanjang bulanan.',
                    'highlights' => [
                        'Semua fitur Starter',
                        'CRM lite untuk follow-up lead',
                        'Chatbot AI dengan kuota bawaan',
                        '500 AI Credits per bulan + top up tersedia',
                        'WhatsApp API dan WhatsApp Web',
                        'Masa aktif 6 bulan',
                    ],
                    'product_line' => 'omnichannel',
                    'plan_revision' => 'v2',
                    'sales_status' => 'current',
                    'recommended' => true,
                    'audience' => 'Cocok untuk tim yang ingin fokus 6 bulan tanpa repot perpanjang bulanan',
                ],
            ],
            [
                'code' => 'scale-6m-v2',
                'name' => 'Scale',
                'billing_interval' => 'semiannual',
                'is_active' => true,
                'is_public' => true,
                'is_system' => false,
                'sort_order' => 240,
                'features' => [
                    PlanFeature::MULTI_COMPANY => true,
                    PlanFeature::CONVERSATIONS => true,
                    PlanFeature::CRM => true,
                    PlanFeature::COMMERCE => false,
                    PlanFeature::PROJECT_MANAGEMENT => false,
                    PlanFeature::LIVE_CHAT => true,
                    PlanFeature::SOCIAL_MEDIA => true,
                    PlanFeature::CHATBOT_AI => true,
                    PlanFeature::EMAIL_MARKETING => false,
                    PlanFeature::WHATSAPP_API => true,
                    PlanFeature::WHATSAPP_WEB => true,
                    PlanFeature::ADVANCED_REPORTS => true,
                ],
                'limits' => [
                    PlanLimit::COMPANIES => 3,
                    PlanLimit::BRANCHES => 10,
                    PlanLimit::USERS => 50,
                    PlanLimit::PRODUCTS => 5000,
                    PlanLimit::CONTACTS => 50000,
                    PlanLimit::WHATSAPP_INSTANCES => 5,
                    PlanLimit::SOCIAL_ACCOUNTS => 15,
                    PlanLimit::LIVE_CHAT_WIDGETS => 5,
                    PlanLimit::CHATBOT_ACCOUNTS => 10,
                    PlanLimit::EMAIL_INBOX_ACCOUNTS => 3,
                    PlanLimit::EMAIL_CAMPAIGNS => 0,
                    PlanLimit::WA_BLAST_RECIPIENTS_MONTHLY => 10000,
                    PlanLimit::EMAIL_RECIPIENTS_MONTHLY => 0,
                    PlanLimit::AI_CREDITS_MONTHLY => 2500,
                    PlanLimit::CHATBOT_KNOWLEDGE_DOCUMENTS => 200,
                    PlanLimit::AUTOMATION_WORKFLOWS => 0,
                    PlanLimit::AUTOMATION_EXECUTIONS_MONTHLY => 0,
                ],
                'meta' => [
                    'price' => 4794000,
                    'currency' => 'IDR',
                    'tagline' => 'Stack omnichannel lengkap untuk 6 bulan kerja yang lebih stabil.',
                    'description' => 'Paket premium untuk operasional yang butuh kapasitas besar dan ingin lebih tenang menjalankan tim selama 6 bulan.',
                    'highlights' => [
                        'Semua fitur Growth',
                        'CRM lite untuk follow-up lead',
                        '2.500 AI Credits per bulan + top up tersedia',
                        'WhatsApp Web',
                        'Kapasitas user, kontak, dan channel lebih besar',
                        'Masa aktif 6 bulan',
                    ],
                    'product_line' => 'omnichannel',
                    'plan_revision' => 'v2',
                    'sales_status' => 'current',
                    'recommended' => false,
                    'audience' => 'Cocok untuk operasional yang ingin lebih stabil selama 6 bulan',
                ],
            ],
            [
                'code' => 'starter-yearly-v2',
                'name' => 'Starter',
                'billing_interval' => 'yearly',
                'is_active' => true,
                'is_public' => true,
                'is_system' => false,
                'sort_order' => 320,
                'features' => [
                    PlanFeature::MULTI_COMPANY => false,
                    PlanFeature::CONVERSATIONS => true,
                    PlanFeature::CRM => true,
                    PlanFeature::COMMERCE => false,
                    PlanFeature::PROJECT_MANAGEMENT => false,
                    PlanFeature::LIVE_CHAT => true,
                    PlanFeature::SOCIAL_MEDIA => true,
                    PlanFeature::CHATBOT_AI => false,
                    PlanFeature::EMAIL_MARKETING => false,
                    PlanFeature::WHATSAPP_API => false,
                    PlanFeature::WHATSAPP_WEB => false,
                    PlanFeature::ADVANCED_REPORTS => false,
                ],
                'limits' => [
                    PlanLimit::COMPANIES => 1,
                    PlanLimit::BRANCHES => 1,
                    PlanLimit::USERS => 5,
                    PlanLimit::PRODUCTS => 100,
                    PlanLimit::CONTACTS => 2000,
                    PlanLimit::WHATSAPP_INSTANCES => 0,
                    PlanLimit::SOCIAL_ACCOUNTS => 2,
                    PlanLimit::LIVE_CHAT_WIDGETS => 1,
                    PlanLimit::CHATBOT_ACCOUNTS => 0,
                    PlanLimit::EMAIL_INBOX_ACCOUNTS => 0,
                    PlanLimit::EMAIL_CAMPAIGNS => 0,
                    PlanLimit::WA_BLAST_RECIPIENTS_MONTHLY => 0,
                    PlanLimit::EMAIL_RECIPIENTS_MONTHLY => 0,
                    PlanLimit::AI_CREDITS_MONTHLY => 0,
                    PlanLimit::CHATBOT_KNOWLEDGE_DOCUMENTS => 0,
                    PlanLimit::AUTOMATION_WORKFLOWS => 0,
                    PlanLimit::AUTOMATION_EXECUTIONS_MONTHLY => 0,
                ],
                'meta' => [
                    'price' => 1788000,
                    'currency' => 'IDR',
                    'tagline' => 'Starter setahun penuh untuk tim kecil yang ingin lebih tenang menjalankan omnichannel.',
                    'description' => 'Cocok untuk tim kecil yang ingin mengunci social inbox, live chat, dan CRM lite dalam satu paket tahunan.',
                    'highlights' => [
                        'Shared inbox untuk percakapan tim',
                        'CRM lite untuk follow-up lead',
                        'Live chat website',
                        'Social media inbox',
                        'Masa aktif 1 tahun',
                    ],
                    'product_line' => 'omnichannel',
                    'plan_revision' => 'v2',
                    'sales_status' => 'current',
                    'recommended' => false,
                    'audience' => 'Cocok untuk tim kecil yang ingin lebih tenang sampai satu tahun',
                ],
            ],
            [
                'code' => 'growth-yearly-v2',
                'name' => 'Growth',
                'billing_interval' => 'yearly',
                'is_active' => true,
                'is_public' => true,
                'is_system' => false,
                'sort_order' => 330,
                'features' => [
                    PlanFeature::MULTI_COMPANY => true,
                    PlanFeature::CONVERSATIONS => true,
                    PlanFeature::CRM => true,
                    PlanFeature::COMMERCE => false,
                    PlanFeature::PROJECT_MANAGEMENT => false,
                    PlanFeature::LIVE_CHAT => true,
                    PlanFeature::SOCIAL_MEDIA => true,
                    PlanFeature::CHATBOT_AI => true,
                    PlanFeature::EMAIL_MARKETING => false,
                    PlanFeature::WHATSAPP_API => true,
                    PlanFeature::WHATSAPP_WEB => true,
                    PlanFeature::ADVANCED_REPORTS => true,
                ],
                'limits' => [
                    PlanLimit::COMPANIES => 1,
                    PlanLimit::BRANCHES => 3,
                    PlanLimit::USERS => 15,
                    PlanLimit::PRODUCTS => 1000,
                    PlanLimit::CONTACTS => 10000,
                    PlanLimit::WHATSAPP_INSTANCES => 1,
                    PlanLimit::SOCIAL_ACCOUNTS => 5,
                    PlanLimit::LIVE_CHAT_WIDGETS => 2,
                    PlanLimit::CHATBOT_ACCOUNTS => 2,
                    PlanLimit::EMAIL_INBOX_ACCOUNTS => 1,
                    PlanLimit::EMAIL_CAMPAIGNS => 0,
                    PlanLimit::WA_BLAST_RECIPIENTS_MONTHLY => 1500,
                    PlanLimit::EMAIL_RECIPIENTS_MONTHLY => 0,
                    PlanLimit::AI_CREDITS_MONTHLY => 500,
                    PlanLimit::CHATBOT_KNOWLEDGE_DOCUMENTS => 25,
                    PlanLimit::AUTOMATION_WORKFLOWS => 0,
                    PlanLimit::AUTOMATION_EXECUTIONS_MONTHLY => 0,
                ],
                'meta' => [
                    'price' => 4188000,
                    'currency' => 'IDR',
                    'tagline' => 'Paket rekomendasi tahunan untuk tim yang serius membangun omnichannel.',
                    'description' => 'Untuk tim yang ingin AI, WhatsApp API, dan WhatsApp Web berjalan setahun penuh dari akun bisnis sendiri tanpa repot perpanjang bulanan.',
                    'highlights' => [
                        'Semua fitur Starter',
                        'CRM lite untuk follow-up lead',
                        'Chatbot AI dengan kuota bawaan',
                        '500 AI Credits per bulan + top up tersedia',
                        'WhatsApp API dan WhatsApp Web',
                        'Masa aktif 1 tahun',
                    ],
                    'product_line' => 'omnichannel',
                    'plan_revision' => 'v2',
                    'sales_status' => 'current',
                    'recommended' => true,
                    'audience' => 'Cocok untuk tim yang ingin jalan stabil sampai satu tahun',
                ],
            ],
            [
                'code' => 'scale-yearly-v2',
                'name' => 'Scale',
                'billing_interval' => 'yearly',
                'is_active' => true,
                'is_public' => true,
                'is_system' => false,
                'sort_order' => 340,
                'features' => [
                    PlanFeature::MULTI_COMPANY => true,
                    PlanFeature::CONVERSATIONS => true,
                    PlanFeature::CRM => true,
                    PlanFeature::COMMERCE => false,
                    PlanFeature::PROJECT_MANAGEMENT => false,
                    PlanFeature::LIVE_CHAT => true,
                    PlanFeature::SOCIAL_MEDIA => true,
                    PlanFeature::CHATBOT_AI => true,
                    PlanFeature::EMAIL_MARKETING => false,
                    PlanFeature::WHATSAPP_API => true,
                    PlanFeature::WHATSAPP_WEB => true,
                    PlanFeature::ADVANCED_REPORTS => true,
                ],
                'limits' => [
                    PlanLimit::COMPANIES => 3,
                    PlanLimit::BRANCHES => 10,
                    PlanLimit::USERS => 50,
                    PlanLimit::PRODUCTS => 5000,
                    PlanLimit::CONTACTS => 50000,
                    PlanLimit::WHATSAPP_INSTANCES => 5,
                    PlanLimit::SOCIAL_ACCOUNTS => 15,
                    PlanLimit::LIVE_CHAT_WIDGETS => 5,
                    PlanLimit::CHATBOT_ACCOUNTS => 10,
                    PlanLimit::EMAIL_INBOX_ACCOUNTS => 3,
                    PlanLimit::EMAIL_CAMPAIGNS => 0,
                    PlanLimit::WA_BLAST_RECIPIENTS_MONTHLY => 10000,
                    PlanLimit::EMAIL_RECIPIENTS_MONTHLY => 0,
                    PlanLimit::AI_CREDITS_MONTHLY => 2500,
                    PlanLimit::CHATBOT_KNOWLEDGE_DOCUMENTS => 200,
                    PlanLimit::AUTOMATION_WORKFLOWS => 0,
                    PlanLimit::AUTOMATION_EXECUTIONS_MONTHLY => 0,
                ],
                'meta' => [
                    'price' => 9588000,
                    'currency' => 'IDR',
                    'tagline' => 'Paket tahunan untuk operasional besar yang ingin channel lengkap dan ritme kerja lebih tenang.',
                    'description' => 'Paket premium setahun penuh untuk tim yang butuh kapasitas besar, AI, WhatsApp API, dan WhatsApp Web dalam satu workspace.',
                    'highlights' => [
                        'Semua fitur Growth',
                        'CRM lite untuk follow-up lead',
                        '2.500 AI Credits per bulan + top up tersedia',
                        'WhatsApp Web',
                        'Kapasitas user, kontak, dan channel lebih besar',
                        'Masa aktif 1 tahun',
                    ],
                    'product_line' => 'omnichannel',
                    'plan_revision' => 'v2',
                    'sales_status' => 'current',
                    'recommended' => false,
                    'audience' => 'Cocok untuk operasional besar yang ingin stabil sampai satu tahun',
                ],
            ],
        ];

        $rows = array_map(function (array $plan) use ($now): array {
            return [
                'code' => $plan['code'],
                'name' => $plan['name'],
                'billing_interval' => $plan['billing_interval'],
                'is_active' => $plan['is_active'] ? 'true' : 'false',
                'is_public' => $plan['is_public'] ? 'true' : 'false',
                'is_system' => $plan['is_system'] ? 'true' : 'false',
                'sort_order' => $plan['sort_order'],
                'features' => json_encode($plan['features'], JSON_UNESCAPED_UNICODE),
                'limits' => json_encode($plan['limits'], JSON_UNESCAPED_UNICODE),
                'meta' => json_encode($plan['meta'], JSON_UNESCAPED_UNICODE),
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $plans);

        DB::table('subscription_plans')->upsert(
            $rows,
            ['code'],
            [
                'name',
                'billing_interval',
                'is_active',
                'is_public',
                'is_system',
                'sort_order',
                'features',
                'limits',
                'meta',
                'updated_at',
            ]
        );
    }

    public function down(): void
    {
        if (!Schema::hasTable('subscription_plans')) {
            return;
        }

        DB::table('subscription_plans')
            ->whereIn('code', [
                'starter-6m-v2',
                'growth-6m-v2',
                'scale-6m-v2',
                'starter-yearly-v2',
                'growth-yearly-v2',
                'scale-yearly-v2',
            ])
            ->delete();
    }
};
