<?php

return [
    'origin_system' => env('WORKSPACE_FILE_ORIGIN_SYSTEM', 'myapp'),
    'origin_owner' => env('WORKSPACE_FILE_ORIGIN_OWNER', 'first_party'),
    'public_disk' => env('WORKSPACE_PUBLIC_FILESYSTEM_DISK', 'public'),
    'private_disk' => env('WORKSPACE_PRIVATE_FILESYSTEM_DISK', 'private'),

    'categories' => [
        'finance_attachment' => [
            'disk' => env('WORKSPACE_FINANCE_FILESYSTEM_DISK', env('WORKSPACE_PRIVATE_FILESYSTEM_DISK', 'private')),
            'visibility' => 'private',
            'directory' => 'finance/attachments',
            'purpose' => 'finance_attachment',
            'access_class' => 'private_document',
            'share_strategy' => 'authenticated_download',
            'retention_class' => 'business_record',
            'permissions' => ['finance.view'],
        ],
        'payment_proof' => [
            'disk' => env('WORKSPACE_PAYMENT_FILESYSTEM_DISK', env('WORKSPACE_PRIVATE_FILESYSTEM_DISK', 'private')),
            'visibility' => 'private',
            'directory' => 'payments/proofs',
            'purpose' => 'payment_proof',
            'access_class' => 'private_document',
            'share_strategy' => 'authenticated_download',
            'retention_class' => 'business_record',
            'permissions' => ['payments.view'],
        ],
        'bank_statement' => [
            'disk' => env('WORKSPACE_BANK_STATEMENT_FILESYSTEM_DISK', env('WORKSPACE_PRIVATE_FILESYSTEM_DISK', 'private')),
            'visibility' => 'private',
            'directory' => 'finance/reconciliations/statements',
            'purpose' => 'bank_statement',
            'access_class' => 'private_document',
            'share_strategy' => 'authenticated_download',
            'retention_class' => 'business_record',
            'permissions' => ['finance.view-reconciliation', 'finance.view'],
        ],
        'sales_attachment' => [
            'disk' => env('WORKSPACE_SALES_FILESYSTEM_DISK', env('WORKSPACE_PRIVATE_FILESYSTEM_DISK', 'private')),
            'visibility' => 'private',
            'directory' => 'sales/attachments',
            'purpose' => 'sales_attachment',
            'access_class' => 'private_document',
            'share_strategy' => 'authenticated_download',
            'retention_class' => 'business_record',
            'permissions' => ['sales.view'],
        ],
        'channel_shared_media' => [
            'disk' => env('WORKSPACE_CHANNEL_SHARED_FILESYSTEM_DISK', env('WORKSPACE_PRIVATE_FILESYSTEM_DISK', 'private')),
            'visibility' => 'private',
            'directory' => 'channels/shared-media',
            'purpose' => 'channel_shared_media',
            'access_class' => 'channel_shared_media',
            'share_strategy' => 'signed_url',
            'retention_class' => 'operational_media',
            'share_ttl_seconds' => 900,
        ],
        'channel_inbound_evidence' => [
            'disk' => env('WORKSPACE_CHANNEL_INBOUND_FILESYSTEM_DISK', env('WORKSPACE_PRIVATE_FILESYSTEM_DISK', 'private')),
            'visibility' => 'private',
            'directory' => 'channels/inbound-evidence',
            'purpose' => 'channel_inbound_evidence',
            'access_class' => 'channel_inbound_evidence',
            'share_strategy' => 'authenticated_download',
            'retention_class' => 'audit_evidence',
            'copy_policy' => 'important_only',
        ],
        'wa_template_header_media' => [
            'disk' => env('WORKSPACE_WA_TEMPLATE_FILESYSTEM_DISK', env('WORKSPACE_PRIVATE_FILESYSTEM_DISK', 'private')),
            'visibility' => 'private',
            'directory' => 'wa_templates/headers',
            'purpose' => 'wa_template_header_media',
            'access_class' => 'channel_shared_media',
            'share_strategy' => 'signed_url',
            'retention_class' => 'template_media',
            'share_ttl_seconds' => 900,
        ],
        'public_asset' => [
            'disk' => env('WORKSPACE_PUBLIC_FILESYSTEM_DISK', 'public'),
            'visibility' => 'public',
            'purpose' => 'public_asset',
            'access_class' => 'public_asset',
            'share_strategy' => 'public_url',
            'retention_class' => 'public_asset',
        ],
    ],
];
